services:
  app:
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"

  centrifugo:
    ports:
      - "9001:8000"

  redis:
    ports:
      - "6379:6379"

  auth_service:
    ports:
      - "5001:5000"

  auth_db:
    ports:
      - "5439:5432"

  redis_auth:
    ports:
      - "6380:6379"

